# ---------------------------------------------------------------------------
# See the NOTICE file distributed with this work for additional
# information regarding copyright ownership.
#
# This is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of
# the License, or (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA, or see the FSF site: http://www.fsf.org.
# ---------------------------------------------------------------------------
version: '3'

networks:
  bridge:
    driver: bridge
  web:
    external: true

services:

  web:
    # Use an already built XWiki image from DockerHub.
    image: "xwiki:13.9-postgres-tomcat"
    container_name: xwiki
    depends_on:
      - db
    # The DB_USER/DB_PASSWORD/DB_HOST variables are used in the hibernate.cfg.xml file.
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_DATABASE=xwiki
      - DB_HOST=xwiki-postgres-db
    # Provide a name instead of an auto-generated id for the xwiki permanent directory configured in the Dockerfile,
    # to make it simpler to identify in 'docker volume ls'.
    volumes:
      - xwiki-data:/usr/local/xwiki
    networks:
      - bridge
      - web
    expose:
      - 8080
    labels:
      traefik.enable: "true"
      traefik.http.routers.xwiki.entryPoints: web
      traefik.http.routers.xwiki.tls.certResolver: default
      traefik.http.routers.xwiki.rule: Host(`wiki.example.com`)

  # The container that runs PostgreSQL
  db:
    image: "postgres:13.5-alpine"
    container_name: xwiki-postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=xwiki
      - POSTGRES_PASSWORD=xwiki
      - POSTGRES_USER=xwiki
      - POSTGRES_DB=xwiki
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    networks:
      - bridge

volumes:
  postgres-data:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/postgres
      o: bind
  xwiki-data:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/data
      o: bind
